# Generated by Django 6.0.6 on 2026-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="color",
            field=models.CharField(default="#64748b", max_length=7),
        ),
    ]
