# Generated by Django 6.0.6 on 2026-06-12 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0002_column_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="description",
        ),
    ]
