# Generated by Django 6.0.6 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0003_remove_card_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
