# Generated by Django 6.0.6 on 2026-10-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0004_card_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#64748b", "Cinza"),
                            ("#ef4444", "Vermelho"),
                            ("#f97316", "Laranja"),
                            ("#f59e0b", "Âmbar"),
                            ("#10b981", "Esmeralda"),
                            ("#3b82f6", "Azul"),
                            ("#8b5cf6", "Roxo"),
                            ("#ec4899", "Rosa"),
                        ],
                        default="#64748b",
                        max_length=7,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="kanban.board",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="cards", to="kanban.label"
            ),
        ),
    ]
