# Generated by Django 6.0.6 on 2026-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0005_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="card",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
